# Generated by Django 3.1.5 on 2021-01-28 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210128_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcategory',
            name='user',
        ),
    ]
